### ISSUE TITLE
File structure could be confusing for beginners

### ISSUE THREAD

**Issue by igorbarbashin** [leannezhang/boggle-game#1]
It's not critical but could be improved and thus be a better example for beginners how to organize the codebase.

A few things I've noticed:
- `shuffleBoard.js` is located in `components/Common` folder. But it's not a react component. It looks like a file with two helper functions. Maybe better to move it to `src/helpers/`
- `data/TileData.js`. The folder name assumes there's some kind of data. But in fact is a class.
- styles are not co-located with components. Not a big deal but if you agree we could group them together for better maintainability

Please let me know what do you think of it? I can make a PR with some fixes if you agree

**Comment by leannezhang** [comment]
@igorbarbashin can you elaborate on styles? Do you mean it's best to separate the styles by components or group all the styles in one file called games.css?

**Comment by igorbarbashin** [comment]
Yes, I meant to separate them by components. Game.css is already a bit big

**Comment by igorbarbashin** [comment]
Eric's PR is targeting this. Closing
